# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from unicourt_python_sdk.type.associated_norm_party import AssociatedNormParty

class RequiredAssociatedNormPartyResponse(TypedDict):
    associatedNormPartyArray: typing.List[AssociatedNormParty]

    # Next page of results if applicable.
    nextPageAPI: typing.Optional[str]

    # Link to previous page of results.
    previousPageAPI: typing.Optional[str]

    # Total no. of results for this criteria.
    totalCount: int

    # Total no. of pages.
    totalPages: int

class OptionalAssociatedNormPartyResponse(TypedDict, total=False):
    pass

class AssociatedNormPartyResponse(RequiredAssociatedNormPartyResponse, OptionalAssociatedNormPartyResponse):
    pass
