# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from unicourt_python_sdk.type.callback_list_response_case_document_order_callbacks import CallbackListResponseCaseDocumentOrderCallbacks
from unicourt_python_sdk.type.callback_list_response_case_export_callbacks import CallbackListResponseCaseExportCallbacks

class RequiredCallbackListResponse(TypedDict):
    caseDocumentOrderCallbacks: CallbackListResponseCaseDocumentOrderCallbacks

    caseExportCallbacks: CallbackListResponseCaseExportCallbacks

    # Name of the object.
    object: str

class OptionalCallbackListResponse(TypedDict, total=False):
    pass

class CallbackListResponse(RequiredCallbackListResponse, OptionalCallbackListResponse):
    pass
