# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from unicourt_python_sdk.type.case import Case
from unicourt_python_sdk.type.case_update_pacer_options_response import CaseUpdatePacerOptionsResponse
from unicourt_python_sdk.type.exception import Exception

class RequiredCaseUpdate(TypedDict):
    case: Case

    caseAPI: str

    # Unique Id for a Case in UniCourt.
    caseId: str

    exception: Exception

    # Name of the object.
    object: str

    pacerOptions: CaseUpdatePacerOptionsResponse

    # The date and time when the case was last requested for update 
    requestedDate: datetime

    # Status of the request.
    status: str

class OptionalCaseUpdate(TypedDict, total=False):
    pass

class CaseUpdate(RequiredCaseUpdate, OptionalCaseUpdate):
    pass
