# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCaseType(TypedDict):
    areaOfLaw: typing.Optional[str]

    areaOfLawId: typing.Optional[str]

    caseClass: str

    caseClassId: str

    caseTypeGroup: typing.Optional[str]

    caseTypeGroupId: typing.Optional[str]

    caseTypeId: str

    caseTypeTag: typing.Optional[str]

    # The date and time when it was first created. This date and time is in UTC. Formatted as YYYY-MM-DD HH:MM:SS.
    createdDate: datetime

    name: typing.Optional[str]

    object: str

    saliCode: typing.Optional[str]

class OptionalCaseType(TypedDict, total=False):
    pass

class CaseType(RequiredCaseType, OptionalCaseType):
    pass
