# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from unicourt_python_sdk.type.case_class import CaseClass

class RequiredCaseCountAnalyticsByCaseClass(TypedDict):
    caseClass: CaseClass

    caseCount: int

    # Link to cases for this criteria.
    caseSearchAPI: str

    object: str

class OptionalCaseCountAnalyticsByCaseClass(TypedDict, total=False):
    pass

class CaseCountAnalyticsByCaseClass(RequiredCaseCountAnalyticsByCaseClass, OptionalCaseCountAnalyticsByCaseClass):
    pass
