# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from unicourt_python_sdk.type.address import Address
from unicourt_python_sdk.type.email import Email
from unicourt_python_sdk.type.phone import Phone

class RequiredContact(TypedDict):
    # List of available addresses.
    addressArray: typing.Optional[typing.List[Address]]

    # List of available emails.
    emailArray: typing.Optional[typing.List[Email]]

    object: str

    # List of available phone numbers.
    phoneNumberArray: typing.Optional[typing.List[Phone]]

class OptionalContact(TypedDict, total=False):
    pass

class Contact(RequiredContact, OptionalContact):
    pass
