# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from unicourt_python_sdk.type.court import Court

class RequiredCourtResponse(TypedDict):
    courtArray: typing.List[Court]

    # Link to next page.
    nextPageAPI: typing.Optional[str]

    object: str

    pageNumber: int

    # Link to previous page.
    previousPageAPI: typing.Optional[str]

    # The number of matches that were found in the index.
    totalCount: int

    # Total pages for matches that were found in the index.
    totalPages: int

class OptionalCourtResponse(TypedDict, total=False):
    pass

class CourtResponse(RequiredCourtResponse, OptionalCourtResponse):
    pass
