# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from unicourt_python_sdk.type.daily_usage_response_api_calls_billable import DailyUsageResponseApiCallsBillable
from unicourt_python_sdk.type.daily_usage_response_api_calls_credited import DailyUsageResponseApiCallsCredited
from unicourt_python_sdk.type.daily_usage_response_api_calls_made import DailyUsageResponseApiCallsMade

class RequiredDailyUsageResponse(TypedDict):
    apiCallsBillable: DailyUsageResponseApiCallsBillable

    apiCallsCredited: DailyUsageResponseApiCallsCredited

    apiCallsMade: DailyUsageResponseApiCallsMade

    # Api Usage made.
    apiUsage: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

    # Name of the object.
    object: str

    # End time of the usage.
    usageEndTime: datetime

    # Start time of the usage.
    usageStartTime: datetime

class OptionalDailyUsageResponse(TypedDict, total=False):
    pass

class DailyUsageResponse(RequiredDailyUsageResponse, OptionalDailyUsageResponse):
    pass
