# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredEmail(TypedDict):
    # email id
    emailId: str

    # Date at which this record is created in UniCourt.
    firstFetchDate: datetime

    # Boolean indicating if the email is visible or not.
    isVisible: bool

    # Date at which this record was updated in UniCourt.
    lastFetchDate: datetime

    object: str

class OptionalEmail(TypedDict, total=False):
    pass

class Email(RequiredEmail, OptionalEmail):
    pass
