# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from unicourt_python_sdk.type.pacer_credential import PacerCredential

class RequiredPacerCredentialListResponse(TypedDict):
    # Link for the next page.
    nextPageAPI: typing.Optional[str]

    # Name of the object.
    object: str

    # Array of pacer credentials.
    pacerCredentialArray: typing.List[PacerCredential]

    # Current page number.
    pageNumber: int

    # Link for the previous page.
    previousPageAPI: typing.Optional[str]

    # Total number of pacer credentials available.
    totalCount: int

    # Total number of pages available.
    totalPages: int

class OptionalPacerCredentialListResponse(TypedDict, total=False):
    pass

class PacerCredentialListResponse(RequiredPacerCredentialListResponse, OptionalPacerCredentialListResponse):
    pass
