# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPACERSearchPageInfo(TypedDict):
    # Indicates if the current page is the first page.
    first: bool

    # Indicates if the current page is the last page.
    last: bool

    # Current Page number.
    number: int

    # Number of records returned.
    numberOfElements: int

    # Name of the object
    object: str

    # Number of results obtained in a page..
    size: int

    # Total number of records available
    totalElements: int

    # Total pages of data available.
    totalPages: int

class OptionalPACERSearchPageInfo(TypedDict, total=False):
    pass

class PACERSearchPageInfo(RequiredPACERSearchPageInfo, OptionalPACERSearchPageInfo):
    pass
