# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from unicourt_python_sdk.type.possible_norm_law_firm_source_details_linked_norm_attorney_id_array import PossibleNormLawFirmSourceDetailsLinkedNormAttorneyIdArray

class RequiredPossibleNormLawFirmSourceDetails(TypedDict):
    linkedNormAttorneyIdArray: PossibleNormLawFirmSourceDetailsLinkedNormAttorneyIdArray

    source: typing.Optional[str]

class OptionalPossibleNormLawFirmSourceDetails(TypedDict, total=False):
    pass

class PossibleNormLawFirmSourceDetails(RequiredPossibleNormLawFirmSourceDetails, OptionalPossibleNormLawFirmSourceDetails):
    pass
