# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from unicourt_python_sdk.type.raw_ordered_data_child import RawOrderedDataChild

class RequiredRawOrderedData(TypedDict):
    # Any docket text that belongs to the main docket text is added in the child.
    childArray: typing.List[RawOrderedDataChild]

    # Label of the docket from the source.
    lbl: typing.Optional[str]

    # Structure order
    ord: int

    # List of available addresses.
    val: typing.Optional[str]

class OptionalRawOrderedData(TypedDict, total=False):
    pass

class RawOrderedData(RequiredRawOrderedData, OptionalRawOrderedData):
    pass
