# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from unicourt_python_sdk.type.service_status_down_details import ServiceStatusDownDetails

class RequiredServiceStatus(TypedDict):
    # Name of the object
    object: str

    # Status Details of Case Update Services Status.
    serviceDetails: str

    serviceStatusDownDetails: ServiceStatusDownDetails

    # Status of Case Update Services Status.
    serviceUp: bool

class OptionalServiceStatus(TypedDict, total=False):
    pass

class ServiceStatus(RequiredServiceStatus, OptionalServiceStatus):
    pass
