# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import unicourt_python_sdk
from unicourt_python_sdk.model.attorney_type_response import AttorneyTypeResponse
from unicourt_python_sdk import configuration


class TestAttorneyTypeResponse(unittest.TestCase):
    """AttorneyTypeResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
