# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import unicourt_python_sdk
from unicourt_python_sdk.model.bar_source_data_ten_year_discipline_array_item import BarSourceDataTenYearDisciplineArrayItem
from unicourt_python_sdk import configuration


class TestBarSourceDataTenYearDisciplineArrayItem(unittest.TestCase):
    """BarSourceDataTenYearDisciplineArrayItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
