# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from unicourt_python_sdk import schemas  # noqa: F401


class AccessTokenIdListResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "AccessTokenIdArray",
            "object",
        }
        
        class properties:
            
            
            class AccessTokenIdArray(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    max_items = 10
                    min_items = 0
                    
                    @staticmethod
                    def items() -> typing.Type['AccessTokenIdResponse']:
                        return AccessTokenIdResponse
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['AccessTokenIdResponse'], typing.List['AccessTokenIdResponse']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'AccessTokenIdArray':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'AccessTokenIdResponse':
                    return super().__getitem__(i)
            
            
            class object(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 25
                    min_length = 25
            __annotations__ = {
                "AccessTokenIdArray": AccessTokenIdArray,
                "object": object,
            }
    
    AccessTokenIdArray: MetaOapg.properties.AccessTokenIdArray
    object: MetaOapg.properties.object
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["AccessTokenIdArray"]) -> MetaOapg.properties.AccessTokenIdArray: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["object"]) -> MetaOapg.properties.object: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["AccessTokenIdArray", "object", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["AccessTokenIdArray"]) -> MetaOapg.properties.AccessTokenIdArray: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["object"]) -> MetaOapg.properties.object: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["AccessTokenIdArray", "object", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        AccessTokenIdArray: typing.Union[MetaOapg.properties.AccessTokenIdArray, list, tuple, ],
        object: typing.Union[MetaOapg.properties.object, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AccessTokenIdListResponse':
        return super().__new__(
            cls,
            *args,
            AccessTokenIdArray=AccessTokenIdArray,
            object=object,
            _configuration=_configuration,
            **kwargs,
        )

from unicourt_python_sdk.model.access_token_id_response import AccessTokenIdResponse
