# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from unicourt_python_sdk import schemas  # noqa: F401


class CallbackListResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "caseDocumentOrderCallbacks",
            "caseExportCallbacks",
            "object",
        }
        
        class properties:
        
            @staticmethod
            def caseDocumentOrderCallbacks() -> typing.Type['CallbackListResponseCaseDocumentOrderCallbacks']:
                return CallbackListResponseCaseDocumentOrderCallbacks
        
            @staticmethod
            def caseExportCallbacks() -> typing.Type['CallbackListResponseCaseExportCallbacks']:
                return CallbackListResponseCaseExportCallbacks
            
            
            class object(
                schemas.StrSchema
            ):
                pass
            __annotations__ = {
                "caseDocumentOrderCallbacks": caseDocumentOrderCallbacks,
                "caseExportCallbacks": caseExportCallbacks,
                "object": object,
            }
    
    caseDocumentOrderCallbacks: 'CallbackListResponseCaseDocumentOrderCallbacks'
    caseExportCallbacks: 'CallbackListResponseCaseExportCallbacks'
    object: MetaOapg.properties.object
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["caseDocumentOrderCallbacks"]) -> 'CallbackListResponseCaseDocumentOrderCallbacks': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["caseExportCallbacks"]) -> 'CallbackListResponseCaseExportCallbacks': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["object"]) -> MetaOapg.properties.object: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["caseDocumentOrderCallbacks", "caseExportCallbacks", "object", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["caseDocumentOrderCallbacks"]) -> 'CallbackListResponseCaseDocumentOrderCallbacks': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["caseExportCallbacks"]) -> 'CallbackListResponseCaseExportCallbacks': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["object"]) -> MetaOapg.properties.object: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["caseDocumentOrderCallbacks", "caseExportCallbacks", "object", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        caseDocumentOrderCallbacks: 'CallbackListResponseCaseDocumentOrderCallbacks',
        caseExportCallbacks: 'CallbackListResponseCaseExportCallbacks',
        object: typing.Union[MetaOapg.properties.object, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CallbackListResponse':
        return super().__new__(
            cls,
            *args,
            caseDocumentOrderCallbacks=caseDocumentOrderCallbacks,
            caseExportCallbacks=caseExportCallbacks,
            object=object,
            _configuration=_configuration,
            **kwargs,
        )

from unicourt_python_sdk.model.callback_list_response_case_document_order_callbacks import CallbackListResponseCaseDocumentOrderCallbacks
from unicourt_python_sdk.model.callback_list_response_case_export_callbacks import CallbackListResponseCaseExportCallbacks
