# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from unicourt_python_sdk import schemas  # noqa: F401


class CaseType(
    schemas.DictBase,
    schemas.NoneBase,
    schemas.Schema,
    schemas.NoneFrozenDictMixin
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "caseClassId",
            "caseTypeGroup",
            "caseTypeId",
            "caseTypeGroupId",
            "createdDate",
            "areaOfLaw",
            "caseTypeTag",
            "name",
            "caseClass",
            "areaOfLawId",
            "saliCode",
            "object",
        }
        
        class properties:
            
            
            class areaOfLaw(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 255
                    min_length = 1
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'areaOfLaw':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class areaOfLawId(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 18
                    min_length = 18
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'areaOfLawId':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class caseClass(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 255
                    min_length = 1
            
            
            class caseClassId(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 18
                    min_length = 18
            
            
            class caseTypeGroup(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 255
                    min_length = 1
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'caseTypeGroup':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class caseTypeGroupId(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 18
                    min_length = 18
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'caseTypeGroupId':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class caseTypeId(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 18
                    min_length = 18
            
            
            class caseTypeTag(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 255
                    min_length = 1
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'caseTypeTag':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class createdDate(
                schemas.DateTimeSchema
            ):
            
            
                class MetaOapg:
                    format = 'date-time'
                    max_length = 255
                    min_length = 1
            
            
            class name(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 255
                    min_length = 1
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'name':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class object(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 8
                    min_length = 8
            
            
            class saliCode(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    max_length = 255
                    min_length = 1
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'saliCode':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "areaOfLaw": areaOfLaw,
                "areaOfLawId": areaOfLawId,
                "caseClass": caseClass,
                "caseClassId": caseClassId,
                "caseTypeGroup": caseTypeGroup,
                "caseTypeGroupId": caseTypeGroupId,
                "caseTypeId": caseTypeId,
                "caseTypeTag": caseTypeTag,
                "createdDate": createdDate,
                "name": name,
                "object": object,
                "saliCode": saliCode,
            }

    
    caseClassId: MetaOapg.properties.caseClassId
    caseTypeGroup: MetaOapg.properties.caseTypeGroup
    caseTypeId: MetaOapg.properties.caseTypeId
    caseTypeGroupId: MetaOapg.properties.caseTypeGroupId
    createdDate: MetaOapg.properties.createdDate
    areaOfLaw: MetaOapg.properties.areaOfLaw
    caseTypeTag: MetaOapg.properties.caseTypeTag
    name: MetaOapg.properties.name
    caseClass: MetaOapg.properties.caseClass
    areaOfLawId: MetaOapg.properties.areaOfLawId
    saliCode: MetaOapg.properties.saliCode
    object: MetaOapg.properties.object
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["areaOfLaw"]) -> MetaOapg.properties.areaOfLaw: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["areaOfLawId"]) -> MetaOapg.properties.areaOfLawId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["caseClass"]) -> MetaOapg.properties.caseClass: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["caseClassId"]) -> MetaOapg.properties.caseClassId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["caseTypeGroup"]) -> MetaOapg.properties.caseTypeGroup: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["caseTypeGroupId"]) -> MetaOapg.properties.caseTypeGroupId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["caseTypeId"]) -> MetaOapg.properties.caseTypeId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["caseTypeTag"]) -> MetaOapg.properties.caseTypeTag: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createdDate"]) -> MetaOapg.properties.createdDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["object"]) -> MetaOapg.properties.object: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["saliCode"]) -> MetaOapg.properties.saliCode: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["areaOfLaw", "areaOfLawId", "caseClass", "caseClassId", "caseTypeGroup", "caseTypeGroupId", "caseTypeId", "caseTypeTag", "createdDate", "name", "object", "saliCode", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["areaOfLaw"]) -> MetaOapg.properties.areaOfLaw: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["areaOfLawId"]) -> MetaOapg.properties.areaOfLawId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["caseClass"]) -> MetaOapg.properties.caseClass: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["caseClassId"]) -> MetaOapg.properties.caseClassId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["caseTypeGroup"]) -> MetaOapg.properties.caseTypeGroup: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["caseTypeGroupId"]) -> MetaOapg.properties.caseTypeGroupId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["caseTypeId"]) -> MetaOapg.properties.caseTypeId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["caseTypeTag"]) -> MetaOapg.properties.caseTypeTag: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createdDate"]) -> MetaOapg.properties.createdDate: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["object"]) -> MetaOapg.properties.object: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["saliCode"]) -> MetaOapg.properties.saliCode: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["areaOfLaw", "areaOfLawId", "caseClass", "caseClassId", "caseTypeGroup", "caseTypeGroupId", "caseTypeId", "caseTypeTag", "createdDate", "name", "object", "saliCode", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, None, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CaseType':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
            **kwargs,
        )
