# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from unicourt_python_sdk import schemas  # noqa: F401


class Charge(
    schemas.DictBase,
    schemas.NoneBase,
    schemas.Schema,
    schemas.NoneFrozenDictMixin
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "createdDate",
            "chargeId",
            "name",
            "chargeGroupId",
            "chargeGroup",
            "object",
        }
        
        class properties:
            
            
            class chargeGroup(
                schemas.StrSchema
            ):
                pass
            
            
            class chargeGroupId(
                schemas.StrSchema
            ):
                pass
            
            
            class chargeId(
                schemas.StrSchema
            ):
                pass
            
            
            class createdDate(
                schemas.DateTimeSchema
            ):
                pass
            
            
            class name(
                schemas.StrSchema
            ):
                pass
            
            
            class object(
                schemas.StrSchema
            ):
                pass
            __annotations__ = {
                "chargeGroup": chargeGroup,
                "chargeGroupId": chargeGroupId,
                "chargeId": chargeId,
                "createdDate": createdDate,
                "name": name,
                "object": object,
            }

    
    createdDate: MetaOapg.properties.createdDate
    chargeId: MetaOapg.properties.chargeId
    name: MetaOapg.properties.name
    chargeGroupId: MetaOapg.properties.chargeGroupId
    chargeGroup: MetaOapg.properties.chargeGroup
    object: MetaOapg.properties.object
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["chargeGroup"]) -> MetaOapg.properties.chargeGroup: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["chargeGroupId"]) -> MetaOapg.properties.chargeGroupId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["chargeId"]) -> MetaOapg.properties.chargeId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createdDate"]) -> MetaOapg.properties.createdDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["object"]) -> MetaOapg.properties.object: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["chargeGroup", "chargeGroupId", "chargeId", "createdDate", "name", "object", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["chargeGroup"]) -> MetaOapg.properties.chargeGroup: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["chargeGroupId"]) -> MetaOapg.properties.chargeGroupId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["chargeId"]) -> MetaOapg.properties.chargeId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createdDate"]) -> MetaOapg.properties.createdDate: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["object"]) -> MetaOapg.properties.object: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["chargeGroup", "chargeGroupId", "chargeId", "createdDate", "name", "object", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, None, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Charge':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
            **kwargs,
        )
