# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from unicourt_python_sdk import schemas  # noqa: F401


class NormJudgePublicDataEducationArray(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    The Education History of the judge.
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['NormJudgePublicDataEducationArrayItem']:
            return NormJudgePublicDataEducationArrayItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['NormJudgePublicDataEducationArrayItem'], typing.List['NormJudgePublicDataEducationArrayItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'NormJudgePublicDataEducationArray':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'NormJudgePublicDataEducationArrayItem':
        return super().__getitem__(i)

from unicourt_python_sdk.model.norm_judge_public_data_education_array_item import NormJudgePublicDataEducationArrayItem
