# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from unicourt_python_sdk import schemas  # noqa: F401


class PossibleNormPartyScoreConstituents(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "address",
            "nameSimilarityScore",
            "phone",
            "otherPotentialNormParties",
            "email",
            "secretaryOfStateId",
        }
        
        class properties:
            
            
            class address(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def MATCHED(cls):
                    return cls("Matched")
                
                @schemas.classproperty
                def MISMATCHED(cls):
                    return cls("Mismatched")
                
                @schemas.classproperty
                def NOT_PROVIDED_BY_DATA_SOURCE(cls):
                    return cls("Not_Provided_By_Data_Source")
            
            
            class email(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def MATCHED(cls):
                    return cls("Matched")
                
                @schemas.classproperty
                def MISMATCHED(cls):
                    return cls("Mismatched")
                
                @schemas.classproperty
                def NOT_PROVIDED_BY_DATA_SOURCE(cls):
                    return cls("Not_Provided_By_Data_Source")
            nameSimilarityScore = schemas.Float32Schema
            otherPotentialNormParties = schemas.IntSchema
            
            
            class phone(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def MATCHED(cls):
                    return cls("Matched")
                
                @schemas.classproperty
                def MISMATCHED(cls):
                    return cls("Mismatched")
                
                @schemas.classproperty
                def NOT_PROVIDED_BY_DATA_SOURCE(cls):
                    return cls("Not_Provided_By_Data_Source")
            
            
            class secretaryOfStateId(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def MATCHED(cls):
                    return cls("Matched")
                
                @schemas.classproperty
                def MISMATCHED(cls):
                    return cls("Mismatched")
                
                @schemas.classproperty
                def NOT_PROVIDED_BY_DATA_SOURCE(cls):
                    return cls("Not_Provided_By_Data_Source")
            __annotations__ = {
                "address": address,
                "email": email,
                "nameSimilarityScore": nameSimilarityScore,
                "otherPotentialNormParties": otherPotentialNormParties,
                "phone": phone,
                "secretaryOfStateId": secretaryOfStateId,
            }
    
    address: MetaOapg.properties.address
    nameSimilarityScore: MetaOapg.properties.nameSimilarityScore
    phone: MetaOapg.properties.phone
    otherPotentialNormParties: MetaOapg.properties.otherPotentialNormParties
    email: MetaOapg.properties.email
    secretaryOfStateId: MetaOapg.properties.secretaryOfStateId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["address"]) -> MetaOapg.properties.address: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nameSimilarityScore"]) -> MetaOapg.properties.nameSimilarityScore: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["otherPotentialNormParties"]) -> MetaOapg.properties.otherPotentialNormParties: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["phone"]) -> MetaOapg.properties.phone: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["secretaryOfStateId"]) -> MetaOapg.properties.secretaryOfStateId: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["address", "email", "nameSimilarityScore", "otherPotentialNormParties", "phone", "secretaryOfStateId", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["address"]) -> MetaOapg.properties.address: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email"]) -> MetaOapg.properties.email: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nameSimilarityScore"]) -> MetaOapg.properties.nameSimilarityScore: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["otherPotentialNormParties"]) -> MetaOapg.properties.otherPotentialNormParties: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["phone"]) -> MetaOapg.properties.phone: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["secretaryOfStateId"]) -> MetaOapg.properties.secretaryOfStateId: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["address", "email", "nameSimilarityScore", "otherPotentialNormParties", "phone", "secretaryOfStateId", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        address: typing.Union[MetaOapg.properties.address, str, ],
        nameSimilarityScore: typing.Union[MetaOapg.properties.nameSimilarityScore, decimal.Decimal, int, float, ],
        phone: typing.Union[MetaOapg.properties.phone, str, ],
        otherPotentialNormParties: typing.Union[MetaOapg.properties.otherPotentialNormParties, decimal.Decimal, int, ],
        email: typing.Union[MetaOapg.properties.email, str, ],
        secretaryOfStateId: typing.Union[MetaOapg.properties.secretaryOfStateId, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PossibleNormPartyScoreConstituents':
        return super().__new__(
            cls,
            *args,
            address=address,
            nameSimilarityScore=nameSimilarityScore,
            phone=phone,
            otherPotentialNormParties=otherPotentialNormParties,
            email=email,
            secretaryOfStateId=secretaryOfStateId,
            _configuration=_configuration,
            **kwargs,
        )
