# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from unicourt_python_sdk import schemas  # noqa: F401


class RawOrderedDataChildChildArray(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    Any docket text that belongs to the main docket text is added in the child.
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['RawOrderedDataChildChildArrayItem']:
            return RawOrderedDataChildChildArrayItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['RawOrderedDataChildChildArrayItem'], typing.List['RawOrderedDataChildChildArrayItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'RawOrderedDataChildChildArray':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'RawOrderedDataChildChildArrayItem':
        return super().__getitem__(i)

from unicourt_python_sdk.model.raw_ordered_data_child_child_array_item import RawOrderedDataChildChildArrayItem
