# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from unicourt_python_sdk import schemas  # noqa: F401


class RelatedCase(
    schemas.DictBase,
    schemas.NoneBase,
    schemas.Schema,
    schemas.NoneFrozenDictMixin
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "additionalSourceData",
            "caseNumber",
            "caseId",
            "caseAPI",
            "caseName",
            "isVisible",
            "sourceCaseRelationshipType",
            "caseRelationshipType",
            "object",
        }
        
        class properties:
        
            @staticmethod
            def additionalSourceData() -> typing.Type['SourceStructuredData']:
                return SourceStructuredData
            
            
            class caseAPI(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'caseAPI':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class caseId(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'caseId':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class caseName(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'caseName':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            
            
            class caseNumber(
                schemas.StrSchema
            ):
                pass
        
            @staticmethod
            def caseRelationshipType() -> typing.Type['CaseRelationshipType']:
                return CaseRelationshipType
            isVisible = schemas.BoolSchema
            
            
            class object(
                schemas.StrSchema
            ):
                pass
            
            
            class sourceCaseRelationshipType(
                schemas.StrSchema
            ):
                pass
            __annotations__ = {
                "additionalSourceData": additionalSourceData,
                "caseAPI": caseAPI,
                "caseId": caseId,
                "caseName": caseName,
                "caseNumber": caseNumber,
                "caseRelationshipType": caseRelationshipType,
                "isVisible": isVisible,
                "object": object,
                "sourceCaseRelationshipType": sourceCaseRelationshipType,
            }

    
    additionalSourceData: 'SourceStructuredData'
    caseNumber: MetaOapg.properties.caseNumber
    caseId: MetaOapg.properties.caseId
    caseAPI: MetaOapg.properties.caseAPI
    caseName: MetaOapg.properties.caseName
    isVisible: MetaOapg.properties.isVisible
    sourceCaseRelationshipType: MetaOapg.properties.sourceCaseRelationshipType
    caseRelationshipType: 'CaseRelationshipType'
    object: MetaOapg.properties.object
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["additionalSourceData"]) -> 'SourceStructuredData': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["caseAPI"]) -> MetaOapg.properties.caseAPI: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["caseId"]) -> MetaOapg.properties.caseId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["caseName"]) -> MetaOapg.properties.caseName: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["caseNumber"]) -> MetaOapg.properties.caseNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["caseRelationshipType"]) -> 'CaseRelationshipType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isVisible"]) -> MetaOapg.properties.isVisible: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["object"]) -> MetaOapg.properties.object: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sourceCaseRelationshipType"]) -> MetaOapg.properties.sourceCaseRelationshipType: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["additionalSourceData", "caseAPI", "caseId", "caseName", "caseNumber", "caseRelationshipType", "isVisible", "object", "sourceCaseRelationshipType", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["additionalSourceData"]) -> 'SourceStructuredData': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["caseAPI"]) -> MetaOapg.properties.caseAPI: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["caseId"]) -> MetaOapg.properties.caseId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["caseName"]) -> MetaOapg.properties.caseName: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["caseNumber"]) -> MetaOapg.properties.caseNumber: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["caseRelationshipType"]) -> 'CaseRelationshipType': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isVisible"]) -> MetaOapg.properties.isVisible: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["object"]) -> MetaOapg.properties.object: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sourceCaseRelationshipType"]) -> MetaOapg.properties.sourceCaseRelationshipType: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["additionalSourceData", "caseAPI", "caseId", "caseName", "caseNumber", "caseRelationshipType", "isVisible", "object", "sourceCaseRelationshipType", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, None, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RelatedCase':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
            **kwargs,
        )

from unicourt_python_sdk.model.case_relationship_type import CaseRelationshipType
from unicourt_python_sdk.model.source_structured_data import SourceStructuredData
