# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from unicourt_python_sdk.pydantic.case_timeline import CaseTimeline
from unicourt_python_sdk.pydantic.sos_data_preview import SOSDataPreview

class AssociatedNormParty(BaseModel):
    case_count: int = Field(alias='caseCount')

    # Link to related cases for this association.
    case_search_a_p_i: str = Field(alias='caseSearchAPI')

    case_timeline: CaseTimeline = Field(alias='caseTimeline')

    name: str = Field(alias='name')

    # Link to Details for the Party.
    norm_party_a_p_i: str = Field(alias='normPartyAPI')

    norm_party_id: str = Field(alias='normPartyId')

    object: str = Field(alias='object')

    sos_data_array: typing.List[SOSDataPreview] = Field(alias='sosDataArray')
    class Config:
        arbitrary_types_allowed = True
