# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from unicourt_python_sdk.pydantic.contact import Contact

class AssociatedSoSPerson(BaseModel):
    contact: Contact = Field(alias='contact')

    entity_name: str = Field(alias='entityName')

    entity_type: Literal["Partner", "Agent", "CEO", "Partner/General Member", "Partner/GeneralMember"] = Field(alias='entityType')

    object: str = Field(alias='object')
    class Config:
        arbitrary_types_allowed = True
