# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class CaseAnalyticsAPI(BaseModel):
    case_count_analytics_by_area_of_law_a_p_i: str = Field(alias='caseCountAnalyticsByAreaOfLawAPI')

    case_count_analytics_by_case_class_a_p_i: str = Field(alias='caseCountAnalyticsByCaseClassAPI')

    case_count_analytics_by_case_type_a_p_i: str = Field(alias='caseCountAnalyticsByCaseTypeAPI')

    case_count_analytics_by_case_type_group_a_p_i: str = Field(alias='caseCountAnalyticsByCaseTypeGroupAPI')

    case_count_analytics_by_court_a_p_i: str = Field(alias='caseCountAnalyticsByCourtAPI')

    case_count_analytics_by_court_location_a_p_i: str = Field(alias='caseCountAnalyticsByCourtLocationAPI')

    case_count_analytics_by_court_system_a_p_i: str = Field(alias='caseCountAnalyticsByCourtSystemAPI')

    case_count_analytics_by_court_type_a_p_i: str = Field(alias='caseCountAnalyticsByCourtTypeAPI')

    case_count_analytics_by_jurisdiction_geo_a_p_i: str = Field(alias='caseCountAnalyticsByJurisdictionGeoAPI')

    case_count_analytics_by_party_role_a_p_i: typing.Optional[str] = Field(alias='caseCountAnalyticsByPartyRoleAPI')

    case_count_analytics_by_party_role_group_a_p_i: typing.Optional[str] = Field(alias='caseCountAnalyticsByPartyRoleGroupAPI')

    object: str = Field(alias='object')

    total_cases: int = Field(alias='totalCases')
    class Config:
        arbitrary_types_allowed = True
