# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class CourtLocation(BaseModel):
    # City
    city: typing.Optional[str] = Field(alias='city')

    court_location_id: str = Field(alias='courtLocationId')

    court_service_status_a_p_i: typing.Optional[str] = Field(alias='courtServiceStatusAPI')

    courts_for_court_location_a_p_i: str = Field(alias='courtsForCourtLocationAPI')

    # The date and time when it was first created. This date and time is in UTC. Formatted as YYYY-MM-DD HH:MM:SS.
    created_date: datetime = Field(alias='createdDate')

    name: str = Field(alias='name')

    object: str = Field(alias='object')

    # State Name if present else default value.
    state_name: str = Field(alias='stateName')

    # 1st part of the street address.
    street_address1: typing.Optional[str] = Field(alias='streetAddress1')

    # 2nd part of the street address.
    street_address2: typing.Optional[str] = Field(alias='streetAddress2')
    class Config:
        arbitrary_types_allowed = True
