# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class DocumentDownload(BaseModel):
    # API call to download the document again if the above fileUrl is expired.
    case_document_download_a_p_i: str = Field(alias='caseDocumentDownloadAPI')

    # Requested Document ID.
    case_document_id: str = Field(alias='caseDocumentId')

    # Expiry date-time for the fileUrl provided in this object.
    expiry_date: str = Field(alias='expiryDate')

    # Link to download the file.
    file_url: str = Field(alias='fileUrl')

    # Name of the object.
    object: str = Field(alias='object')
    class Config:
        arbitrary_types_allowed = True
