# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from unicourt_python_sdk.pydantic.contact import Contact
from unicourt_python_sdk.pydantic.norm_judge_public_data_aba_ratings import NormJudgePublicDataAbaRatings
from unicourt_python_sdk.pydantic.norm_judge_public_data_alias_array import NormJudgePublicDataAliasArray
from unicourt_python_sdk.pydantic.norm_judge_public_data_bio import NormJudgePublicDataBio
from unicourt_python_sdk.pydantic.norm_judge_public_data_education_array import NormJudgePublicDataEducationArray
from unicourt_python_sdk.pydantic.norm_judge_public_data_judicial_source import NormJudgePublicDataJudicialSource
from unicourt_python_sdk.pydantic.norm_judge_public_data_name_history_array import NormJudgePublicDataNameHistoryArray
from unicourt_python_sdk.pydantic.norm_judge_public_data_professional_career_array import NormJudgePublicDataProfessionalCareerArray
from unicourt_python_sdk.pydantic.service_history import ServiceHistory

class NormJudgePublicData(BaseModel):
    aba_ratings: NormJudgePublicDataAbaRatings = Field(alias='abaRatings')

    alias_array: NormJudgePublicDataAliasArray = Field(alias='aliasArray')

    bio: NormJudgePublicDataBio = Field(alias='bio')

    contact: Contact = Field(alias='contact')

    education_array: NormJudgePublicDataEducationArray = Field(alias='educationArray')

    first_fetch_date: typing.Optional[datetime] = Field(alias='firstFetchDate')

    judicial_source: NormJudgePublicDataJudicialSource = Field(alias='judicialSource')

    # The judicial status of the Judge
    judicial_status: typing.Optional[str] = Field(alias='judicialStatus')

    last_fetch_date: typing.Optional[datetime] = Field(alias='lastFetchDate')

    # Last Fetch Date of the Judge Update.
    last_fetch_date_with_updates: typing.Optional[datetime] = Field(alias='lastFetchDateWithUpdates')

    name_history_array: NormJudgePublicDataNameHistoryArray = Field(alias='nameHistoryArray')

    object: str = Field(alias='object')

    professional_career_array: NormJudgePublicDataProfessionalCareerArray = Field(alias='professionalCareerArray')

    # Judicial History of the Judge.
    service_history_array: typing.List[ServiceHistory] = Field(alias='serviceHistoryArray')
    class Config:
        arbitrary_types_allowed = True
