# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class PACERSearchPageInfo(BaseModel):
    # Indicates if the current page is the first page.
    first: bool = Field(alias='first')

    # Indicates if the current page is the last page.
    last: bool = Field(alias='last')

    # Current Page number.
    number: int = Field(alias='number')

    # Number of records returned.
    number_of_elements: int = Field(alias='numberOfElements')

    # Name of the object
    object: str = Field(alias='object')

    # Number of results obtained in a page..
    size: int = Field(alias='size')

    # Total number of records available
    total_elements: int = Field(alias='totalElements')

    # Total pages of data available.
    total_pages: int = Field(alias='totalPages')
    class Config:
        arbitrary_types_allowed = True
