# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from unicourt_python_sdk.pydantic.possible_norm_judge_score_constituents import PossibleNormJudgeScoreConstituents

class PossibleNormJudge(BaseModel):
    associated_norm_attorneys_a_p_i: str = Field(alias='associatedNormAttorneysAPI')

    associated_norm_law_firms_a_p_i: str = Field(alias='associatedNormLawFirmsAPI')

    associated_norm_parties_a_p_i: str = Field(alias='associatedNormPartiesAPI')

    best_match: bool = Field(alias='bestMatch')

    case_count_analytics_by_norm_judge_a_p_i: str = Field(alias='caseCountAnalyticsByNormJudgeAPI')

    confidence_score: typing.Optional[typing.Union[int, float]] = Field(alias='confidenceScore')

    # Link to Details For the Judge.
    norm_judge_a_p_i: str = Field(alias='normJudgeAPI')

    norm_judge_id: str = Field(alias='normJudgeId')

    norm_judge_name: str = Field(alias='normJudgeName')

    # Name of the object
    object: str = Field(alias='object')

    score_constituents: PossibleNormJudgeScoreConstituents = Field(alias='scoreConstituents')
    class Config:
        arbitrary_types_allowed = True
