# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from unicourt_python_sdk.pydantic.raw_ordered_data_child_child_array import RawOrderedDataChildChildArray

class RawOrderedDataChild(BaseModel):
    child_array: RawOrderedDataChildChildArray = Field(alias='childArray')

    # Label of the docket from the source.
    lbl: typing.Optional[str] = Field(alias='lbl')

    # Structure order.
    ord: int = Field(alias='ord')

    # List of available addresses.
    val: typing.Optional[str] = Field(alias='val')
    class Config:
        arbitrary_types_allowed = True
