# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from unicourt_python_sdk.pydantic.extracted_fields import ExtractedFields
from unicourt_python_sdk.pydantic.raw_ordered_data import RawOrderedData

class SourceStructuredData(BaseModel):
    extracted_fields: ExtractedFields = Field(alias='extractedFields')

    raw_ordered_data_array: typing.List[RawOrderedData] = Field(alias='rawOrderedDataArray')
    class Config:
        arbitrary_types_allowed = True
