# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from unicourt_python_sdk.paths.norm_attorney_norm_attorney_id_associated_norm_law_firms.get import GetAssociatedLawFirms
from unicourt_python_sdk.paths.norm_attorney_norm_attorney_id_associated_norm_judges.get import GetJudgesAssociatedWithAttorney
from unicourt_python_sdk.paths.norm_attorney_norm_attorney_id.get import GetNormAttorneyById
from unicourt_python_sdk.paths.norm_attorney_search_norm_attorney_search_id.get import GetNormAttorneySearchResults
from unicourt_python_sdk.paths.norm_attorney_norm_attorney_id_associated_norm_parties.get import ListAssociatedNormParties
from unicourt_python_sdk.paths.norm_attorney_search.get import SearchAttorneyInfo
from unicourt_python_sdk.apis.tags.attorney_analytics_api_api_raw import AttorneyAnalyticsAPIApiRaw


class AttorneyAnalyticsAPIApi(
    GetAssociatedLawFirms,
    GetJudgesAssociatedWithAttorney,
    GetNormAttorneyById,
    GetNormAttorneySearchResults,
    ListAssociatedNormParties,
    SearchAttorneyInfo,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AttorneyAnalyticsAPIApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AttorneyAnalyticsAPIApiRaw(api_client)
