# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from unicourt_python_sdk.paths.case_update.put import AddCaseUpdateForCaseId
from unicourt_python_sdk.paths.case_updates.get import GetCaseUpdates
from unicourt_python_sdk.paths.case_update_case_id.get import GetCaseUpdatesByCaseId
from unicourt_python_sdk.apis.tags.case_update_api_api_raw import CaseUpdateAPIApiRaw


class CaseUpdateAPIApi(
    AddCaseUpdateForCaseId,
    GetCaseUpdates,
    GetCaseUpdatesByCaseId,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CaseUpdateAPIApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CaseUpdateAPIApiRaw(api_client)
