# coding: utf-8

"""
    UniCourt Enterprise APIs

    <button><a href=\"/enterpriseapi/download/UniCourt-Enterprise-API-Spec.yaml\" >Download UniCourt Enterprise APIs Specification</a></button> 

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from unicourt_python_sdk.paths.norm_judge_norm_judge_id_associated_norm_parties.get import GetAssociatedNormParties
from unicourt_python_sdk.paths.norm_judge_norm_judge_id.get import GetNormJudgeDetails
from unicourt_python_sdk.paths.norm_judge_search_norm_judge_search_id.get import GetNormJudgeSearchResultsById
from unicourt_python_sdk.paths.norm_judge_norm_judge_id_associated_norm_attorneys.get import ListAssociatedNormAttorneys
from unicourt_python_sdk.paths.norm_judge_norm_judge_id_associated_norm_law_firms.get import ListLawFirmsAssociatedWithJudge
from unicourt_python_sdk.paths.norm_judge_search.get import SearchNormJudges
from unicourt_python_sdk.apis.tags.judge_analytics_api_api_raw import JudgeAnalyticsAPIApiRaw


class JudgeAnalyticsAPIApi(
    GetAssociatedNormParties,
    GetNormJudgeDetails,
    GetNormJudgeSearchResultsById,
    ListAssociatedNormAttorneys,
    ListLawFirmsAssociatedWithJudge,
    SearchNormJudges,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: JudgeAnalyticsAPIApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = JudgeAnalyticsAPIApiRaw(api_client)
